import React, { useState } from 'react';
import { usePlatform } from '../context/PlatformContext';
import { 
  ShieldCheck, 
  Download, 
  FileSpreadsheet, 
  TrendingUp, 
  Building2, 
  DollarSign, 
  Award, 
  PieChart, 
  Layers, 
  ExternalLink,
  CheckCircle2,
  FileCheck2,
  Printer,
  ChevronDown,
  Sparkles,
  Search,
  FileText
} from 'lucide-react';
import { TOTAL_ANNUAL_TARGET_AMT, TOTAL_ANNUAL_TARGET_CR, INSTITUTES } from '../data/seedData';
import confetti from 'canvas-confetti';

export function CarsExecutiveDashboardView({ onOpenProject }) {
  const { 
    projects, 
    totalRealizedRevenue, 
    totalSanctionedAmount, 
    totalPatentsCount, 
    totalPrototypesCount,
    totalStartupsCount,
    totalPublicationsCount,
    totalTargetAchievementPct,
    instituteStats,
    inquiries,
    setIsReportModalOpen
  } = usePlatform();

  const [activeTab, setActiveTab] = useState('overview'); // 'overview' | 'rankings' | 'institutes' | 'inquiries'
  const [downloadSuccess, setDownloadSuccess] = useState('');

  const formatCurrency = (amt) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(amt || 0);
  };

  // Group funding sources
  const govtRevenue = projects.filter(p => p.fundingSourceType === 'Government').reduce((acc, p) => acc + (p.realizedAmount || 0), 0);
  const industryRevenue = projects.filter(p => p.fundingSourceType === 'Industry Partner').reduce((acc, p) => acc + (p.realizedAmount || 0), 0);
  const seedRevenue = projects.filter(p => p.fundingSourceType === 'Internal Seed Grant').reduce((acc, p) => acc + (p.realizedAmount || 0), 0);

  // Group TRL distribution
  const trlBasic = projects.filter(p => p.trl <= 3).length;
  const trlDemo = projects.filter(p => p.trl >= 4 && p.trl <= 6).length;
  const trlDeploy = projects.filter(p => p.trl >= 7).length;

  // Export 1: NIRF RPC Data Format
  const exportNirfRpc = () => {
    const sponsored = projects.filter(p => p.category === 'Sponsored Research');
    const consultancy = projects.filter(p => p.category === 'Contract R&D' || p.category === 'Consultancy');

    const csvRows = [
      ['GANPAT UNIVERSITY - NIRF RESEARCH & PROFESSIONAL PRACTICE (RPC) DATA CAPTURE'],
      ['Generated by CARS Platform on ' + new Date().toLocaleDateString()],
      [],
      ['TABLE 1: SPONSORED RESEARCH PROJECTS (FSR)'],
      ['Project ID', 'Project Title', 'Funding Agency', 'Financial Year', 'Sanctioned Amount (INR)', 'Amount Received (INR)', 'Principal Investigator', 'Institute'],
      ...sponsored.map(p => [
        p.id,
        `"${p.title.replace(/"/g, '""')}"`,
        `"${p.fundingAgency}"`,
        '2024-25',
        p.sanctionedAmount,
        p.realizedAmount,
        `"${p.principalInvestigator?.name}"`,
        p.instituteId
      ]),
      [],
      ['TABLE 2: CONSULTANCY PROJECTS (FCP)'],
      ['Project ID', 'Consultancy Title', 'Client Organization', 'Financial Year', 'Contract Amount (INR)', 'Received In Cash (INR)', 'Principal Investigator', 'Institute'],
      ...consultancy.map(p => [
        p.id,
        `"${p.title.replace(/"/g, '""')}"`,
        `"${p.fundingAgency}"`,
        '2024-25',
        p.sanctionedAmount,
        p.realizedAmount,
        `"${p.principalInvestigator?.name}"`,
        p.instituteId
      ])
    ];

    const csvContent = "data:text/csv;charset=utf-8," + csvRows.map(e => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `NIRF_RPC_Data_Ganpat_University_${new Date().getFullYear()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    confetti({ particleCount: 50, spread: 70 });
    setDownloadSuccess('NIRF RPC CSV generated and downloaded!');
    setTimeout(() => setDownloadSuccess(''), 4000);
  };

  // Export 2: NAAC Criterion 3 Data Format
  const exportNaacCriterion3 = () => {
    const csvRows = [
      ['GANPAT UNIVERSITY - NAAC CRITERION 3: RESEARCH, INNOVATIONS & EXTENSION'],
      ['Prepared by Centre for Advanced Research Studies (CARS)'],
      [],
      ['METRIC 3.2.1: EXTRAMURAL FUNDING FOR RESEARCH (GOVT & NON-GOVT)'],
      ['Project Title', 'Name of Principal Investigator', 'Department', 'Year of Award', 'Funds Provided (INR in Lakhs)', 'Funding Agency', 'Govt / Non-Govt'],
      ...projects.map(p => [
        `"${p.title.replace(/"/g, '""')}"`,
        `"${p.principalInvestigator?.name}"`,
        `"${p.department}"`,
        '2024-25',
        (p.sanctionedAmount / 100000).toFixed(2),
        `"${p.fundingAgency}"`,
        p.fundingSourceType === 'Government' ? 'Government' : 'Non-Government / Industry'
      ]),
      [],
      ['METRIC 3.4.3: PATENTS PUBLISHED AND GRANTED'],
      ['Patent Title', 'Name of Inventor(s)', 'Application No', 'Status (Published/Granted)', 'Date of Filing/Grant', 'Institute'],
      ...projects.flatMap(p => (p.patents || []).map(pat => [
        `"${pat.title.replace(/"/g, '""')}"`,
        `"${p.principalInvestigator?.name}"`,
        pat.appNo,
        pat.status,
        pat.date || '2024',
        p.instituteId
      ])),
      [],
      ['METRIC 3.5.1: REVENUE GENERATED FROM CONSULTANCY AND CORPORATE TRAINING'],
      ['Consultancy Project Title', 'Consultant Name', 'Consulting Agency', 'Revenue Generated (INR in Lakhs)', 'Institute'],
      ...projects.filter(p => p.category === 'Contract R&D' || p.category === 'Consultancy').map(p => [
        `"${p.title.replace(/"/g, '""')}"`,
        `"${p.principalInvestigator?.name}"`,
        `"${p.fundingAgency}"`,
        (p.realizedAmount / 100000).toFixed(2),
        p.instituteId
      ])
    ];

    const csvContent = "data:text/csv;charset=utf-8," + csvRows.map(e => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `NAAC_Criterion_3_Data_Template_GUNI_${new Date().getFullYear()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    confetti({ particleCount: 50, spread: 70 });
    setDownloadSuccess('NAAC Criterion 3 Data Template downloaded!');
    setTimeout(() => setDownloadSuccess(''), 4000);
  };

  return (
    <div className="space-y-8 pb-16 animate-in fade-in duration-300">
      {/* Executive Header Banner */}
      <div className="rounded-3xl bg-gradient-to-r from-brand-950 via-slate-900 to-indigo-950 text-white p-8 shadow-xl border border-slate-800">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="space-y-2 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/20 border border-purple-400/30 text-purple-300 text-xs font-semibold uppercase tracking-wider">
              <ShieldCheck className="w-4 h-4 text-purple-400" />
              Executive Oversight: Dr. Ajay Kumar Gupta & Dr. Heena Patel
            </div>
            <h1 className="text-2xl lg:text-3xl font-extrabold tracking-tight">
              CARS University-Wide Research & Ranking Dashboard
            </h1>
            <p className="text-slate-300 text-xs sm:text-sm">
              Live revenue monitoring against the <strong>₹4.25 Crore annual target</strong>, accreditation exports for NIRF and NAAC, and cross-institute performance analytics.
            </p>
          </div>

          {/* Ranking Action Buttons */}
          <div className="flex flex-wrap items-center gap-2.5 shrink-0">
            <button
              onClick={() => setIsReportModalOpen(true)}
              className="px-5 py-2.5 bg-gradient-to-r from-guni-crimson to-red-700 hover:from-guni-crimsonDark hover:to-guni-crimson text-white font-extrabold rounded-xl text-xs shadow-lg shadow-red-950/40 border border-amber-400/40 flex items-center gap-2 transition-all hover:scale-102 active:scale-98"
              title="Generate Publication-Grade PDF under Dr. Heena Patel & GUNI"
            >
              <FileText className="w-4 h-4 text-amber-300" />
              <span>Generate Official Report (PDF)</span>
            </button>
            <button
              onClick={exportNirfRpc}
              className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white font-bold rounded-xl text-xs shadow border border-slate-700 flex items-center gap-1.5 transition-all"
            >
              <FileSpreadsheet className="w-3.5 h-3.5 text-blue-400" />
              <span>NIRF CSV</span>
            </button>
            <button
              onClick={exportNaacCriterion3}
              className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white font-bold rounded-xl text-xs shadow border border-slate-700 flex items-center gap-1.5 transition-all"
            >
              <Download className="w-3.5 h-3.5 text-emerald-400" />
              <span>NAAC CSV</span>
            </button>
          </div>
        </div>

        {downloadSuccess && (
          <div className="mt-4 p-3 bg-emerald-500/20 border border-emerald-400/40 text-emerald-300 rounded-xl text-xs font-semibold flex items-center gap-2 animate-in fade-in">
            <CheckCircle2 className="w-4 h-4" />
            {downloadSuccess}
          </div>
        )}

        {/* Master Revenue Target Progress Gauge */}
        <div className="mt-8 pt-6 border-t border-slate-800">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-3">
            <div>
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                Total University Research & Consultancy Realization
              </span>
              <div className="flex items-baseline gap-3 mt-1">
                <span className="text-3xl font-black text-emerald-400">{formatCurrency(totalRealizedRevenue)}</span>
                <span className="text-slate-400 text-sm">Target: ₹{TOTAL_ANNUAL_TARGET_CR} Cr (₹{TOTAL_ANNUAL_TARGET_AMT.toLocaleString('en-IN')})</span>
              </div>
            </div>
            <div className="text-right">
              <span className="text-3xl font-black text-blue-300">{totalTargetAchievementPct}%</span>
              <span className="text-xs text-slate-400 block font-medium">Annual Target Achieved</span>
            </div>
          </div>

          <div className="w-full bg-slate-800 h-4 rounded-full overflow-hidden p-0.5 border border-slate-700">
            <div 
              className="bg-gradient-to-r from-blue-500 via-indigo-500 to-emerald-400 h-full rounded-full transition-all duration-1000"
              style={{ width: `${totalTargetAchievementPct}%` }}
            ></div>
          </div>
        </div>
      </div>

      {/* Navigation Sub-Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-200 pb-2">
        <button
          onClick={() => setActiveTab('overview')}
          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all ${
            activeTab === 'overview' ? 'bg-brand-900 text-white' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          Institutional Overview
        </button>
        <button
          onClick={() => setActiveTab('institutes')}
          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all ${
            activeTab === 'institutes' ? 'bg-brand-900 text-white' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          Institute Quotas ({INSTITUTES.length})
        </button>
        <button
          onClick={() => setActiveTab('rankings')}
          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all ${
            activeTab === 'rankings' ? 'bg-brand-900 text-white' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          NIRF & NAAC Filing Engine
        </button>
        <button
          onClick={() => setActiveTab('inquiries')}
          className={`px-4 py-2 text-xs font-bold rounded-xl transition-all flex items-center gap-1.5 ${
            activeTab === 'inquiries' ? 'bg-brand-900 text-white' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <span>Industry Leads</span>
          <span className="bg-blue-100 text-blue-800 text-[10px] px-1.5 py-0.2 rounded-full font-bold">
            {inquiries.length}
          </span>
        </button>
      </div>

      {/* TAB 1: OVERVIEW & ANALYTICS */}
      {activeTab === 'overview' && (
        <div className="space-y-6">
          {/* 4 Macro Pillar Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-sm">
              <span className="text-xs text-slate-500 font-semibold block mb-1">Approved Grants</span>
              <span className="text-xl font-extrabold text-slate-900">{formatCurrency(totalSanctionedAmount)}</span>
              <span className="text-[11px] text-blue-600 block mt-1">{projects.length} Total Projects</span>
            </div>
            <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-sm">
              <span className="text-xs text-purple-700 font-semibold block mb-1">Patents Registered</span>
              <span className="text-xl font-extrabold text-purple-800">{totalPatentsCount}</span>
              <span className="text-[11px] text-purple-600 block mt-1">NAAC Metric 3.4.3 Ready</span>
            </div>
            <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-sm">
              <span className="text-xs text-amber-700 font-semibold block mb-1">Prototypes Validated</span>
              <span className="text-xl font-extrabold text-amber-800">{totalPrototypesCount}</span>
              <span className="text-[11px] text-amber-600 block mt-1">TRL 5-8 Stage Assets</span>
            </div>
            <div className="p-5 bg-white rounded-2xl border border-slate-200 shadow-sm">
              <span className="text-xs text-emerald-700 font-semibold block mb-1">Active Spinoffs / Startups</span>
              <span className="text-xl font-extrabold text-emerald-800">{totalStartupsCount}</span>
              <span className="text-[11px] text-emerald-600 block mt-1">GUNI Incubation Cell</span>
            </div>
          </div>

          {/* Breakdown Grids */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Funding Source Breakdown */}
            <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm space-y-4">
              <h3 className="font-bold text-base text-slate-900 flex items-center gap-2">
                <PieChart className="w-5 h-5 text-brand-800" />
                Revenue Breakdown by Funding Source
              </h3>
              <div className="space-y-3">
                <div>
                  <div className="flex justify-between text-xs font-semibold mb-1">
                    <span className="text-slate-700">Government Bodies (DST, DBT, ANRF, ICAR)</span>
                    <span className="text-emerald-700 font-bold">{formatCurrency(govtRevenue)}</span>
                  </div>
                  <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                    <div 
                      className="bg-emerald-500 h-full rounded-full" 
                      style={{ width: `${(govtRevenue / (totalRealizedRevenue || 1)) * 100}%` }}
                    ></div>
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold mb-1">
                    <span className="text-slate-700">Corporate & Industry R&D Contracts</span>
                    <span className="text-blue-700 font-bold">{formatCurrency(industryRevenue)}</span>
                  </div>
                  <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                    <div 
                      className="bg-blue-600 h-full rounded-full" 
                      style={{ width: `${(industryRevenue / (totalRealizedRevenue || 1)) * 100}%` }}
                    ></div>
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold mb-1">
                    <span className="text-slate-700">Internal Seed Funds & Student SSIP Grants</span>
                    <span className="text-purple-700 font-bold">{formatCurrency(seedRevenue)}</span>
                  </div>
                  <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                    <div 
                      className="bg-purple-600 h-full rounded-full" 
                      style={{ width: `${(seedRevenue / (totalRealizedRevenue || 1)) * 100}%` }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>

            {/* TRL Pipeline Breakdown */}
            <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm space-y-4">
              <h3 className="font-bold text-base text-slate-900 flex items-center gap-2">
                <Layers className="w-5 h-5 text-indigo-600" />
                Technology Readiness Level (TRL) Funnel
              </h3>
              <div className="space-y-3 text-xs">
                <div className="p-3 bg-amber-50 rounded-xl border border-amber-200 flex justify-between items-center">
                  <div>
                    <strong className="text-amber-900 block">TRL 1–3: Fundamental R&D / Proof of Concept</strong>
                    <span className="text-slate-500 text-[11px]">Lab studies & formulation trials</span>
                  </div>
                  <span className="font-black text-amber-900 text-lg">{trlBasic}</span>
                </div>

                <div className="p-3 bg-blue-50 rounded-xl border border-blue-200 flex justify-between items-center">
                  <div>
                    <strong className="text-blue-900 block">TRL 4–6: Functional Lab & Pilot Prototypes</strong>
                    <span className="text-slate-500 text-[11px]">Simulated & operational validation</span>
                  </div>
                  <span className="font-black text-blue-900 text-lg">{trlDemo}</span>
                </div>

                <div className="p-3 bg-emerald-50 rounded-xl border border-emerald-200 flex justify-between items-center">
                  <div>
                    <strong className="text-emerald-900 block">TRL 7–9: Ready for Commercialization & Licensing</strong>
                    <span className="text-slate-500 text-[11px]">Deployment in operational customer environment</span>
                  </div>
                  <span className="font-black text-emerald-900 text-lg">{trlDeploy}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: INSTITUTE QUOTAS */}
      {activeTab === 'institutes' && (
        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-6 border-b border-slate-100 flex justify-between items-center">
            <div>
              <h3 className="text-base font-bold text-slate-900">Institute-wise Annual Target Performance (₹4.25 Cr Matrix)</h3>
              <p className="text-xs text-slate-500">Official benchmarks from the CARS Proposal Document.</p>
            </div>
            <span className="text-xs font-semibold text-slate-500">12 Constituent Institutes Tracked</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 text-slate-700 font-bold border-b border-slate-200 uppercase text-[10px]">
                <tr>
                  <th className="p-3 pl-6">Constituent Institute</th>
                  <th className="p-3 text-right">Annual Target</th>
                  <th className="p-3 text-right">Realized Cash (₹)</th>
                  <th className="p-3">Quota Progress</th>
                  <th className="p-3 text-center">Projects</th>
                  <th className="p-3 pr-6 text-right">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {instituteStats.map(inst => (
                  <tr key={inst.id} className="hover:bg-slate-50/80">
                    <td className="p-3 pl-6 font-bold text-slate-900">
                      {inst.name}
                    </td>
                    <td className="p-3 text-right font-bold text-slate-800">
                      ₹{inst.targetCr} Cr
                    </td>
                    <td className="p-3 text-right font-extrabold text-emerald-700">
                      {formatCurrency(inst.realized)}
                    </td>
                    <td className="p-3 w-48">
                      <div className="flex items-center gap-2">
                        <div className="flex-1 bg-slate-200 h-2 rounded-full overflow-hidden">
                          <div 
                            className="bg-brand-800 h-full rounded-full" 
                            style={{ width: `${inst.percent}%` }}
                          ></div>
                        </div>
                        <span className="font-bold text-[11px] text-slate-700">{inst.percent}%</span>
                      </div>
                    </td>
                    <td className="p-3 text-center font-bold text-slate-700">
                      {inst.projectCount}
                    </td>
                    <td className="p-3 pr-6 text-right">
                      {inst.isMet ? (
                        <span className="text-[10px] font-bold bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded-full border border-emerald-200">
                          Quota Met
                        </span>
                      ) : (
                        <span className="text-[10px] font-bold bg-amber-100 text-amber-800 px-2 py-0.5 rounded-full border border-amber-200">
                          In Progress
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* TAB 3: RANKINGS ENGINE */}
      {activeTab === 'rankings' && (
        <div className="space-y-6">
          {/* Hero PDF Generation Card */}
          <div className="p-6 bg-gradient-to-br from-red-50 via-white to-amber-50/50 rounded-3xl border-2 border-guni-crimson/30 shadow-md space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-guni-crimson text-white flex items-center justify-center shadow-md">
                  <ShieldCheck className="w-7 h-7 text-amber-300" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-black text-base text-slate-900 font-serif">
                      Official CARS Institutional Research Report (PDF)
                    </h3>
                    <span className="text-[10px] font-bold bg-amber-100 text-amber-900 border border-amber-300 px-2 py-0.5 rounded uppercase">
                      Executive Signed
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 mt-0.5">
                    Authorized document issued under the seal of <strong>Dr. Heena Patel (Deputy Director)</strong> and <strong>Ganpat University</strong>.
                  </p>
                </div>
              </div>

              <button
                onClick={() => setIsReportModalOpen(true)}
                className="px-5 py-2.5 bg-gradient-to-r from-guni-crimson to-red-800 hover:from-guni-crimsonDark hover:to-guni-crimson text-white font-extrabold rounded-xl text-xs shadow-md border border-amber-300/40 flex items-center justify-center gap-2 transition-all hover:scale-102 active:scale-98 shrink-0"
              >
                <Download className="w-4 h-4 text-amber-300" />
                <span>Configure & Generate PDF</span>
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2 text-[11px] text-slate-600 border-t border-red-100">
              <div className="bg-white/80 p-2.5 rounded-xl border border-red-100/80">
                <strong className="text-slate-800 block">✓ Statutory Letterhead & Motto</strong>
                <span>Official GUNI Sanskrit motto & NAAC Grade 'A' badge</span>
              </div>
              <div className="bg-white/80 p-2.5 rounded-xl border border-red-100/80">
                <strong className="text-slate-800 block">✓ Quota Achievement Matrix</strong>
                <span>12-institute financial realization vs ₹4.25 Cr target</span>
              </div>
              <div className="bg-white/80 p-2.5 rounded-xl border border-red-100/80">
                <strong className="text-slate-800 block">✓ Regulatory Accreditation Tables</strong>
                <span>NIRF FSR/FCP & NAAC Metric 3.2.1, 3.4.3 & 3.5.1</span>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* NIRF Card */}
            <div className="p-6 bg-white rounded-3xl border-2 border-blue-200 shadow-sm space-y-4">
              <div className="flex justify-between items-start">
                <div className="w-10 h-10 rounded-xl bg-blue-100 text-blue-900 flex items-center justify-center font-black">
                  NIRF
                </div>
                <span className="text-[10px] font-bold bg-blue-50 text-blue-700 border border-blue-200 px-2 py-0.5 rounded uppercase">
                  RPC Parameter
                </span>
              </div>
              <h3 className="font-bold text-base text-slate-900">National Institutional Ranking Framework (NIRF)</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Direct export of <strong>Funded Sponsored Research (FSR)</strong> and <strong>Funded Consultancy Projects (FCP)</strong>. Automatically computes audited amounts received in cash and attaches verified sanction letter citations.
              </p>
              <div className="pt-2">
                <button
                  onClick={exportNirfRpc}
                  className="w-full py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl text-xs flex items-center justify-center gap-2 shadow"
                >
                  <Download className="w-4 h-4" />
                  Download Verified NIRF DCS (CSV)
                </button>
              </div>
            </div>

            {/* NAAC Card */}
            <div className="p-6 bg-white rounded-3xl border-2 border-emerald-200 shadow-sm space-y-4">
              <div className="flex justify-between items-start">
                <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-900 flex items-center justify-center font-black">
                  NAAC
                </div>
                <span className="text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded uppercase">
                  Criterion 3
                </span>
              </div>
              <h3 className="font-bold text-base text-slate-900">NAAC Accreditation Compliance Exporter</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Formats institutional research data into official NAAC Excel Data Templates:
                <strong> Metric 3.2.1</strong> (Extramural research grants), <strong>Metric 3.4.3</strong> (Patents), and <strong>Metric 3.5.1</strong> (Consultancy revenue).
              </p>
              <div className="pt-2">
                <button
                  onClick={exportNaacCriterion3}
                  className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl text-xs flex items-center justify-center gap-2 shadow"
                >
                  <Download className="w-4 h-4" />
                  Download NAAC Data Template (CSV)
                </button>
              </div>
            </div>
          </div>

          {/* Live Preview Table of Exportable Data */}
          <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 space-y-4">
            <div className="flex justify-between items-center">
              <h3 className="font-bold text-slate-900 text-sm">Real-time Ranking Compliance Ledger (Current FY)</h3>
              <span className="text-xs text-slate-500">{projects.length} Audited Records</span>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-50 text-slate-700 font-bold border-b border-slate-200 uppercase text-[10px]">
                  <tr>
                    <th className="p-2.5">Project ID</th>
                    <th className="p-2.5">Title</th>
                    <th className="p-2.5">Agency</th>
                    <th className="p-2.5">Category</th>
                    <th className="p-2.5 text-right">Sanctioned</th>
                    <th className="p-2.5 text-right">Realized</th>
                    <th className="p-2.5">Sanction Proof</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {projects.slice(0, 6).map(p => (
                    <tr key={p.id} className="hover:bg-slate-50">
                      <td className="p-2.5 font-mono text-slate-600">{p.id}</td>
                      <td className="p-2.5 font-semibold text-slate-900 truncate max-w-xs">{p.title}</td>
                      <td className="p-2.5 text-slate-600">{p.fundingAgency}</td>
                      <td className="p-2.5">{p.category}</td>
                      <td className="p-2.5 text-right font-bold text-slate-700">{formatCurrency(p.sanctionedAmount)}</td>
                      <td className="p-2.5 text-right font-bold text-emerald-700">{formatCurrency(p.realizedAmount)}</td>
                      <td className="p-2.5 text-slate-500 font-mono text-[10px]">{p.sanctionLetter || 'Verified_PDF'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: INDUSTRY LEADS & INQUIRIES */}
      {activeTab === 'inquiries' && (
        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 space-y-4">
          <div className="flex justify-between items-center">
            <div>
              <h3 className="font-bold text-base text-slate-900">External Corporate Consultancy Leads</h3>
              <p className="text-xs text-slate-500">Inquiries submitted via the Public Showcase Portal.</p>
            </div>
            <span className="text-xs font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-3 py-1 rounded-full">
              {inquiries.length} Active Leads
            </span>
          </div>

          <div className="divide-y divide-slate-100">
            {inquiries.map(inq => (
              <div key={inq.id} className="py-4 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-xs text-slate-900">{inq.clientName}</span>
                    <span className="text-[10px] text-brand-900 bg-brand-50 border border-brand-200 px-2 py-0.2 rounded font-semibold">
                      {inq.targetInstitute}
                    </span>
                    <span className="text-[10px] text-slate-400">{inq.date}</span>
                  </div>
                  <p className="text-xs text-slate-700 font-medium">{inq.serviceRequested}</p>
                  <div className="text-xs text-slate-500 flex gap-4">
                    <span><strong>Contact:</strong> {inq.contactPerson} ({inq.email})</span>
                    <span><strong>Est. Budget:</strong> {inq.budgetEstimated}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <span className="px-3 py-1 bg-amber-50 text-amber-800 border border-amber-200 rounded-xl text-xs font-bold">
                    {inq.status}
                  </span>
                  <button 
                    onClick={() => alert(`Assigned lead ${inq.id} to Institute Coordinator for ${inq.targetInstitute}`)}
                    className="px-3 py-1 bg-brand-900 hover:bg-brand-950 text-white rounded-xl text-xs font-bold transition-colors"
                  >
                    Assign to PI
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
